version: '3'
services:
  web:
    image: aliexpress-scraper
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: aliexpressdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

# version: '3'
# services:
#   web:
#     build: .
#     command: python app.py
#     volumes:
#       - .:/usr/src/app
#     ports:
#       - "5000:5000"
#     depends_on:
#       - db

#   db:
#     image: postgres:latest
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: mydatabase
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"

#   aliexpress-scraper:
#     image: aliexpress-scraper
#     build: .
#     ports:
#       - "8000:5000"
