version: '3'
services:
  web:
    image: slaymut/aliexpress-scraper:latest
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - postgresdb
  postgresdb:
    image: slaymut/postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: aliexpressdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"